- name: リポジトリ 導入
  dnf:
    disable_gpg_check: yes
    name: https://www.rdoproject.org/repos/rdo-release.el8.rpm

- name: PowerTools
  shell: dnf config-manager --set-enabled powertools

- name: openstackインストール
  dnf:
    name:
      - centos-release-openstack-xena
      - python3-openstackclient